name = "inbox-acceptor"
version = "0.1.0"
package = "/home/colin/work/actors/inbox/target/wasm32-unknown-unknown/release/inbox_acceptor.wasm"

[[handler]]
type = "runtime"

[[handler]]
type = "tcp"

[[handler]]
type = "supervisor"

[[handler]]
type = "rpc"

[[handler]]
type = "store"
base_path = "/mnt/main-volume/inbox/store"
store_id = "inbox"
