name = "inbox-smtp-handler"
version = "0.1.0"
package = "/home/colin/work/actors/inbox/target/wasm32-unknown-unknown/release/inbox_smtp_handler.wasm"
static_package = true

[[handler]]
type = "runtime"

[[handler]]
type = "tcp"

[[handler]]
type = "rpc"
