[package]
name = "inbox-mailbox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
packr-guest = { version = "0.24", features = ["derive"] }
packr-abi = { version = "0.24", default-features = false }
theater-guest = { git = "https://github.com/colinrozzi/theater", rev = "cfcd737606758d388ab9d7042932d13e8da23a76" }
